import Link from "next/link";
import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

function ListItemLoading() {
  return (
    <div className="h-16 grid items-center font-medium w-full">
      <div role="status" className="w-full animate-pulse">
        <div className="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-full"></div>
        <span className="sr-only">Loading...</span>
      </div>
    </div>
  );
}

async function ListItem({ id }: { id: number }) {
  await sleep(Math.random() * 3000);

  const post = await fetch(
    `https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`
  ).then(
    (res) => res.json() as Promise<{ title: string; url: string; by: string }>
  );

  return (
    <li className="truncate leading-10 grid items-center font-medium mb-4">
      <h2 className="font-bold">{post.title}</h2>
      <div className="flex justify-between">
        <small className="text-gray-500">
          Nota por: {post.by}
        </small>
        <small>
          <a className="text-blue-500">
            Ir al sitio
          </a>
        </small>
      </div>
    </li>
  );
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const posts = await fetch(
    `https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty&limitToFirst=10&orderBy="$key"`
  ).then((res) => res.json() as Promise<number[]>);
  return (
    <html lang="en">
      <body>
        <header className="bg-yellow-400 text-black text-center text-xl font-semibold p-3">
          Uizard Hackernews Reader
        </header>
        <main className="grid grid-cols-[700px,1fr]">
          <aside className="border-r-2">
            <ul className="px-4">
              {posts.map((id) => {
                return (
                  <Link href={`/${id}`}>
                    <Suspense fallback={<ListItemLoading />}>
                      <ListItem id={id} key={id} />
                    </Suspense>
                  </Link>
                );
              })}
            </ul>
          </aside>
          <section className="">{children}</section>
        </main>
      </body>
    </html>
  );
}
